services:
  xtractor:
    # simple mode - xtractor/xtractor-simple:latest
    # default mode - xtractor/xtractor:latest
    image: xtractor/xtractor-simple:latest
    container_name: xtractor
    restart: unless-stopped
    ports:
      - '8080:8080'
