services:
  xtractor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SIMPLE_MODE: false # false for default mode, true for simple mode
    container_name: xtractor
    ports:
      - '8080:8080'
    restart: unless-stopped
